import type {
  AssuranceSignalRow,
  VesselEngagementLogRow,
  VesselSupportItemRow,
} from "@/lib/persistence/types";

export const assuranceSignalSeedRows: AssuranceSignalRow[] = [
  {
    assurance_signal_id: "assurance-signal-001",
    date_time: "2026-05-21T08:42:00.000Z",
    signal_title: "Class survey request captured from imported email",
    signal_type: "Governance signal",
    source_type: "Email",
    source_name_optional: "Class Surveyor",
    audience: "Superintendent / Technical team",
    related_vessel_optional: "LPG ALFRED TEMILE 10",
    related_department: "Technical Operations",
    summary: "Imported email asked for the latest repair photos and a concise summary note.",
    exact_comment_optional:
      "Please send the latest repair photos and a short summary note for review.",
    evidence_level: "Fact",
    confidence: "High",
    operational_risk: "Evidence request was issued before the reply could be closed out.",
    reputational_risk: "Low",
    governance_risk: "Tracked through the normal superintendent route.",
    required_action: "Collect the photos, attach the report, and keep the case trail visible.",
    action_owner: "Toye Omolade",
    due_date: "2026-05-24",
    status: "Tracking",
    evidence_links: ["EVID-019-1"],
    notes: "Directly evidenced by the imported email.",
    linked_case_id: "CASE-24-019",
    created_at: "2026-05-21T08:45:00.000Z",
    updated_at: "2026-05-21T08:45:00.000Z",
  },
  {
    assurance_signal_id: "assurance-signal-002",
    date_time: "2026-05-21T10:15:00.000Z",
    signal_title: "Anonymous vessel feedback about support visibility",
    signal_type: "Management concern",
    source_type: "Email",
    source_name_optional: "Anonymous management circulation",
    audience: "Management / Superintendent team",
    related_vessel_optional: null,
    related_department: "Technical Operations",
    summary:
      "Anonymous feedback alleged reduced technical support and reduced superintendent ownership. Treat as reported until the missing specifics are attached.",
    exact_comment_optional: null,
    evidence_level: "Reported",
    confidence: "Medium",
    operational_risk: "Potential weakening of the normal support route.",
    reputational_risk: "Possible trust impact with the vessel team.",
    governance_risk: "Unverified report of possible bypass of normal superintendent coordination.",
    required_action:
      "Request specifics and attach evidence before converting this into a support item.",
    action_owner: "Chief of Staff",
    due_date: "2026-05-24",
    status: "Needs specifics",
    evidence_links: [],
    notes:
      "Reported concern regarding possible direct vessel engagement outside normal superintendent communication loop. Supporting evidence not yet attached. To be treated as unverified governance signal pending confirmation.",
    linked_case_id: null,
    created_at: "2026-05-21T10:20:00.000Z",
    updated_at: "2026-05-21T10:20:00.000Z",
  },
  {
    assurance_signal_id: "assurance-signal-003",
    date_time: "2026-05-21T12:10:00.000Z",
    signal_title: "Informal report of possible off-loop vessel contact",
    signal_type: "Governance signal",
    source_type: "Audit comment",
    source_name_optional: "Operations review note",
    audience: "Management",
    related_vessel_optional: "LNG PORTHARCOURT II",
    related_department: "Operations",
    summary:
      "There are informal reports that a vessel may have been contacted outside the usual superintendent loop. Treat as an assumption until supporting evidence is attached.",
    exact_comment_optional:
      "Informal reports suggest possible direct vessel contact outside the normal superintendent communication loop.",
    evidence_level: "Assumption",
    confidence: "Low",
    operational_risk: "Possible breakdown in the support route.",
    reputational_risk: "Possible sensitivity around communication discipline.",
    governance_risk: "Unverified report of off-loop contact requiring confirmation.",
    required_action: "Confirm the vessel, source, and supporting evidence before any action is taken.",
    action_owner: "Chief of Staff",
    due_date: "2026-05-25",
    status: "Open",
    evidence_links: [],
    notes: "Keep this unverified until the evidence trail is attached.",
    linked_case_id: null,
    created_at: "2026-05-21T12:15:00.000Z",
    updated_at: "2026-05-21T12:15:00.000Z",
  },
];

export const vesselSupportItemSeedRows: VesselSupportItemRow[] = [
  {
    support_item_id: "support-item-001",
    vessel: "LPG ALFRED TEMILE 10",
    issue_title: "Request specifics for anonymous technical support concern",
    issue_description:
      "Broad feedback has been captured as a reported concern. Vessel, issue, date raised, person who raised it, expected support, actual response, current status, and required close-out are still needed.",
    date_raised: "2026-05-21",
    raised_by: "Anonymous management circulation",
    category: "Technical",
    priority: "High",
    risk_level: "High",
    superintendent_owner: "Toye Omolade",
    vessel_owner: "Operations",
    office_support_required: "Collect specifics and confirm what support was actually requested.",
    current_status: "Open",
    blocker_type: "Vessel Response",
    last_action_taken: "Requested specifics",
    last_contact_date: "2026-05-21",
    next_action:
      "Capture the missing vessel-specific details and link evidence before any close-out.",
    due_date: "2026-05-24",
    close_out_evidence: "Pending evidence attachment.",
    status: "Tracking",
    evidence_links: [],
    linked_case_id: null,
    source_signal_id: "assurance-signal-002",
    created_at: "2026-05-21T10:45:00.000Z",
    updated_at: "2026-05-21T10:45:00.000Z",
  },
  {
    support_item_id: "support-item-002",
    vessel: "LNG PORTHARCOURT II",
    issue_title: "Class clarification and evidence pack",
    issue_description:
      "Class correspondence needs the latest technical evidence before the close-out can be completed.",
    date_raised: "2026-05-20",
    raised_by: "Class surveyor",
    category: "Class",
    priority: "Medium",
    risk_level: "Medium",
    superintendent_owner: "Toye Omolade",
    vessel_owner: "Technical Department",
    office_support_required: "Compile the repair evidence and confirm the reply path.",
    current_status: "Closed",
    blocker_type: "Class",
    last_action_taken: "Asked for the latest repair evidence.",
    last_contact_date: "2026-05-21",
    next_action: "Collect the repair evidence and prepare the class update.",
    due_date: "2026-05-25",
    close_out_evidence: "Class email and repair photo pack to be linked.",
    status: "Closed",
    evidence_links: ["EVID-011-1"],
    linked_case_id: "CASE-24-011",
    source_signal_id: "assurance-signal-001",
    created_at: "2026-05-21T09:20:00.000Z",
    updated_at: "2026-05-21T09:20:00.000Z",
  },
];

export const vesselEngagementLogSeedRows: VesselEngagementLogRow[] = [
  {
    engagement_log_id: "engagement-log-001",
    vessel: "LPG ALFRED TEMILE 10",
    date_time: "2026-05-21T11:00:00.000Z",
    engagement_type: "Call",
    attendees: ["Superintendent", "Chief Engineer"],
    topics_discussed: ["Support concern clarification", "Evidence request"],
    actions_agreed: ["Request specifics", "Keep issue unverified until evidence is attached"],
    owner: "Toye Omolade",
    due_date: "2026-05-24",
    follow_up_required: true,
    evidence_link: "Call note placeholder",
    linked_case_id: null,
    linked_signal_id: "assurance-signal-002",
    linked_support_item_id: "support-item-001",
    created_at: "2026-05-21T11:05:00.000Z",
    updated_at: "2026-05-21T11:05:00.000Z",
  },
  {
    engagement_log_id: "engagement-log-002",
    vessel: "LNG PORTHARCOURT II",
    date_time: "2026-05-21T13:20:00.000Z",
    engagement_type: "Meeting",
    attendees: ["Superintendent", "Class Surveyor", "Technical Team"],
    topics_discussed: ["Repair evidence", "Close-out plan"],
    actions_agreed: ["Attach the latest evidence pack", "Update the class response"],
    owner: "Toye Omolade",
    due_date: "2026-05-25",
    follow_up_required: true,
    evidence_link: "Meeting note placeholder",
    linked_case_id: "CASE-24-011",
    linked_signal_id: "assurance-signal-001",
    linked_support_item_id: "support-item-002",
    created_at: "2026-05-21T13:30:00.000Z",
    updated_at: "2026-05-21T13:30:00.000Z",
  },
];
