import { supabase } from "@/lib/supabase";

export async function AgentOutputs({
  projectId,
}: {
  projectId: string;
}) {
  const { data: outputs } = await supabase
    .from("agent_outputs")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false });

  const liveOutputs = outputs ?? [];

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-2xl font-bold text-white">
          Agent Outputs
        </h2>

        <p className="mt-1 text-sm text-slate-400">
          Specialist analysis generated by your AI staff.
        </p>
      </div>

      {liveOutputs.length === 0 && (
        <div className="card p-5">
          <p className="text-sm text-slate-400">
            No agent outputs yet. Run a specialist agent from the task board.
          </p>
        </div>
      )}

      <div className="space-y-3">
        {liveOutputs.map((output) => (
          <article key={output.id} className="card p-5">
            <div className="mb-3 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
              <div>
                <p className="text-sm uppercase tracking-[0.2em] text-[#D8A84E]">
                  {output.agent_name}
                </p>

                <h3 className="mt-1 text-xl font-bold text-white">
                  Specialist Report
                </h3>
              </div>

              <span className="rounded-full border border-[#233450] px-3 py-1 text-xs text-slate-300">
                Confidence: {output.confidence || "Medium"}
              </span>
            </div>

            <div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">
              {output.output}
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
