import { supabase } from "@/lib/supabase";

export async function AgentOutputs({
  projectId,
}: {
  projectId: string;
}) {
  const { data: outputs } = await supabase
    .from("agent_outputs")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false });

  const liveOutputs = outputs ?? [];

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-2xl font-bold text-white">
          Agent Outputs
        </h2>

        <p className="mt-1 text-sm text-slate-400">
          Specialist analysis generated by your AI staff.
        </p>
      </div>

      {liveOutputs.length === 0 && (
        <div className="card p-5">
          <p className="text-sm text-slate-400">
            No outputs yet.
          </p>
        </div>
      )}

      <div className="space-y-3">
        {liveOutputs.map((output) => (
          <details
            key={output.id}
            className="card overflow-hidden"
          >
            <summary className="cursor-pointer list-none p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm uppercase tracking-[0.2em] text-[#D8A84E]">
                    {output.agent_name}
                  </p>

                  <h3 className="mt-1 text-lg font-bold text-white">
                    Specialist Report
                  </h3>
                </div>

                <span className="rounded-full border border-[#233450] px-3 py-1 text-xs text-slate-300">
                  {output.confidence}
                </span>
              </div>
            </summary>

            <div className="border-t border-[#233450] px-5 py-5">
              <div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">
                {output.output}
              </div>
            </div>
          </details>
        ))}
      </div>
    </section>
  );
}
