import { supabase } from "@/lib/supabase";

type Props = {
  params: Promise<{
    id: string;
  }>;
};

export default async function PrintableMemoPage({
  params,
}: Props) {
  const { id } = await params;

  const { data: decision } = await supabase
    .from("decisions")
    .select("*")
    .eq("id", id)
    .single();

  if (!decision) {
    return (
      <main className="mx-auto max-w-4xl p-10">
        <h1 className="text-3xl font-bold">Memo not found</h1>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-4xl bg-white p-10 text-black">
      <header className="border-b border-slate-300 pb-6">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-500">
          Staff OS Executive Decision Memo
        </p>

        <h1 className="mt-3 text-4xl font-bold">
          {decision.memo_title ?? "Executive Memo"}
        </h1>

        <div className="mt-4 grid gap-2 text-sm text-slate-600 md:grid-cols-2">
          <p>
            <span className="font-semibold">Generated:</span>{" "}
            {new Date(decision.created_at).toLocaleString()}
          </p>

          <p>
            <span className="font-semibold">Project ID:</span>{" "}
            {decision.project_id}
          </p>
        </div>
      </header>

      <section className="mt-10">
        <h2 className="text-2xl font-bold">Executive Summary</h2>

        <div className="mt-5 whitespace-pre-wrap text-[15px] leading-8 text-slate-800">
          {decision.memo_body ||
            decision.rationale ||
            decision.recommendation ||
            "No memo content available."}
        </div>
      </section>

      <footer className="mt-16 border-t border-slate-300 pt-6 text-xs text-slate-500">
        Generated by Staff OS
      </footer>
    </main>
  );
}